universe        = vanilla
executable      = /data/bfys/gscriven/Ex_rep/RK_PINN/speed/run_nystrom.sh
arguments       =
initialdir      = /data/bfys/gscriven/Ex_rep/RK_PINN
should_transfer_files = NO
output          = /data/bfys/gscriven/Ex_rep/RK_PINN/logs/nystrom.$(Cluster).$(Process).out
error           = /data/bfys/gscriven/Ex_rep/RK_PINN/logs/nystrom.$(Cluster).$(Process).err
log             = /data/bfys/gscriven/Ex_rep/RK_PINN/logs/nystrom.$(Cluster).log
+UseOS          = "el9"
+JobCategory    = "short"
request_gpus    = 1
request_cpus    = 1
request_memory  = 8 GB
request_disk    = 4 GB
requirements    = (GPUs_DeviceName =?= "Tesla V100-PCIE-32GB")
queue 1
